version: '3.8'

services:
  fibonacci-api:
    build: .
    container_name: fibonacci-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fibonacci-network

networks:
  fibonacci-network:
    driver: bridge
